[workspace]
members = ["cangjie-tree-sitter", "service", "agent"]
build-members = ["cangjie-tree-sitter", "service", "agent"]
test-members = ["cangjie-tree-sitter", "service", "agent"]
target-dir = "target"
