[package]
  cjc-version = "1.0.5"
  name = "cangjiecoder"
  description = "Cangjie AI Coding Agent CLI"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[target.x86_64-w64-mingw32]
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["./stdx/dynamic/stdx"]